package proyectoprogra.JFrames;

import javax.swing.JOptionPane;
import proyectoprogra.Globales;
import proyectoprogra.Factura;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

public class AgregarFacturas extends javax.swing.JFrame {

    public AgregarFacturas() {

        initComponents();
        setTitle("Agregar Facturas");
        setLocationRelativeTo(null);
        setResizable(false);
        cargarClientesActivos();
        cargarEmpleadosActivos();
        cargarEquiposActivos();
        calcularNumeroFactura();
        calcularFechaActual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNoFactura = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        checkEstado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbEquipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalleReparcion = new javax.swing.JTextArea();
        txtTotalPagar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbEmpleado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("No. Factura");

        txtNoFactura.setEnabled(false);
        txtNoFactura.setName("txtNoFactura"); // NOI18N
        txtNoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoFacturaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setName("BTNsalir"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.setName("BTNagregar"); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha");

        txtFecha.setName("txtNombre"); // NOI18N

        jLabel6.setText("Estado");

        checkEstado.setSelected(true);
        checkEstado.setEnabled(false);
        checkEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEstadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        jLabel3.setText("Equipo");

        jLabel4.setText("Detalle de Repacion");

        jLabel7.setText("Total a pagar");

        cbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClienteActionPerformed(evt);
            }
        });

        txtDetalleReparcion.setColumns(20);
        txtDetalleReparcion.setLineWrap(true);
        txtDetalleReparcion.setRows(5);
        jScrollPane1.setViewportView(txtDetalleReparcion);

        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        jLabel8.setText("Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkEstado)
                            .addComponent(txtNoFactura)
                            .addComponent(txtFecha)
                            .addComponent(cbCliente, 0, 200, Short.MAX_VALUE)
                            .addComponent(cbEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtTotalPagar)
                            .addComponent(cbEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAgregar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cargarEmpleadosActivos() {
        cbEmpleado.removeAllItems();
        for (int i = 0; i < Globales.Empleados.size(); i++) {
            if (Globales.Empleados.get(i).isEstado() == true) {
                cbEmpleado.addItem(Globales.Empleados.get(i).getNickname()); // esto inserta en el combobox
            }

        }
    }

    public void cargarClientesActivos() {
        cbCliente.removeAllItems();
        for (int i = 0; i < Globales.Clientes.size(); i++) {
            if (Globales.Clientes.get(i).isEstado() == true) {
                cbCliente.addItem(Globales.Clientes.get(i).getNickname()); // esto inserta en el combobox
            }

        }
    }

    public void cargarEquiposActivos() {
        cbEquipo.removeAllItems();
        for (int i = 0; i < Globales.Equipos.size(); i++) {
            if (Globales.Equipos.get(i).getNicknameCliente().equalsIgnoreCase(cbCliente.getSelectedItem().toString())) {
                if (Globales.Equipos.get(i).isEstado() == true) {
                    cbEquipo.addItem(Globales.Equipos.get(i).getNombreEquipo()); // esto inserta en el combobox
                }
            }

        }
    }

    public void calcularNumeroFactura() { // esto sirve para obtener la ultima factura
        int max = 0;
        for (int i = 0; i < Globales.Facturas.size(); i++) {
            if (Globales.Facturas.get(i).getNumeroFactura() > max) {
                max = Globales.Facturas.get(i).getNumeroFactura();
            }
        }
        txtNoFactura.setText(String.valueOf(max + 1));
    }

    public void calcularFechaActual() { // esto sirve para obtener el dia
        Date date = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(dateFormat.format(date));
        txtFecha.setEnabled(false);
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Validamos que la sucursal escribrio todos los datos\
        Factura f = new Factura();

        boolean encontrado = false;

        try {
            if (txtFecha.getText().equalsIgnoreCase("")) {
                throw new Exception("Debe escribir la fecha del dia de hoy");
            }
            if (cbCliente.getSelectedIndex() < 0) {
                throw new Exception("Debe seleccionar el cliente para la factura");
            }
            if (cbEquipo.getSelectedIndex() < 0) {
                throw new Exception("Debe seleccionar un equipo para la factura");
            }
            if (cbEmpleado.getSelectedIndex() < 0) {
                throw new Exception("Debe seleccionar un empleado para la factura");
            }
            if (txtDetalleReparcion.getText().equalsIgnoreCase("")) {
                throw new Exception("Debe escribir un detalle para la factura");
            }
            if (txtTotalPagar.getText().equalsIgnoreCase("")) {
                throw new Exception("Debe escribir el total de la repacion");
            }
            if (isDouble(txtTotalPagar.getText()) == false) {
                throw new Exception("El valor total a pagar no es valido");

            }

            f.setNumeroFactura(Integer.parseInt(txtNoFactura.getText()));
            f.setFecha(txtFecha.getText());
            f.setNicknameCliente(cbCliente.getSelectedItem().toString());
            f.setNombreEquipo(cbEquipo.getSelectedItem().toString());
            f.setNicknameEmpleado(cbEmpleado.getSelectedItem().toString());
            f.setDetalleReparacion(txtDetalleReparcion.getText());
            f.setMontoAPagar(Double.parseDouble(txtTotalPagar.getText()));
            f.setEstado(checkEstado.isSelected());

            // de aqui para abajo es el metodo para agregar una factura
            if (btnAgregar.getText().equalsIgnoreCase("Agregar")) {

                // Este for verifica si ya existe el codigo en la lista de categorias
                for (int i = 0; i < Globales.Facturas.size(); i++) {
                    if (Globales.Facturas.get(i).getNumeroFactura() == f.getNumeroFactura()) {
                        encontrado = true;
                    }
                }
                if (encontrado == true) {
                    throw new Exception("Ya existe una factura con ese numero");
                } else {
                    Globales.Facturas.add(f);
                    JOptionPane.showMessageDialog(null, "La Factura: " + f.getNumeroFactura() + " ha sido agregada exitosamente");
                    this.setVisible(false);
                    new ListadoFacturas().setVisible(true);

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al agregar los datos: " + e.getMessage(), "Error!",
                    JOptionPane.INFORMATION_MESSAGE);
        }

        Globales.guardarFacturas();


    }//GEN-LAST:event_btnAgregarActionPerformed

    private boolean isDouble(String valor) {
        try {
            double n = Double.parseDouble(valor);

        } catch (Exception e) {
            return false;
        }
        return true;
    }

    private void txtNoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoFacturaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        new ListadoFacturas().setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void checkEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEstadoActionPerformed

    private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClienteActionPerformed
       cargarEquiposActivos();
    }//GEN-LAST:event_cbClienteActionPerformed

    public void editarFactura(Factura facturaActual) {
        this.setTitle("Ver Factura");
        btnAgregar.setVisible(false);

        txtNoFactura.setText(String.valueOf(facturaActual.getNumeroFactura()));
        txtNoFactura.setEnabled(false);
        txtFecha.setText(facturaActual.getFecha());
        txtFecha.setEnabled(false);
        cbCliente.setSelectedItem(facturaActual.getNicknameCliente());
        cbCliente.setEnabled(false);
        cbEquipo.setSelectedItem(facturaActual.getNombreEquipo());
        cbEquipo.setEnabled(false);
        cbEmpleado.setSelectedItem(facturaActual.getNicknameEmpleado());
        cbEmpleado.setEnabled(false);
        txtDetalleReparcion.setText(facturaActual.getDetalleReparacion());
        txtDetalleReparcion.setEnabled(false);
        txtTotalPagar.setText(String.valueOf(facturaActual.getMontoAPagar()));
        txtTotalPagar.setEnabled(false);
        checkEstado.setSelected(facturaActual.isEstado());
        checkEstado.setEnabled(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarFacturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JComboBox<String> cbEquipo;
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDetalleReparcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNoFactura;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
